sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "8.0"
cache:
  directories:
    - node_modules
install:
  - npm install jest-cli
  - npm install
# command to run tests
script:
    - npm test -- --coverage